src/objects/Drug_HRB__c.object
<CustomObject>
    <fields>
        <fullName>DrugCode__c</fullName>
        <label>DrugCode</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tableyear2012__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tableyear2012</label>
        <type>Checkbox</type>
    </fields>
    <label>Drug-HRB</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs HRB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of HRB Form</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X16_Date_of_Assessment__c</fullName>
        <label>16 Date of Assessment</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X21a_Date_This_treatment_started__c</fullName>
        <label>21a Date This treatment started</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b12_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b12 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b13_Date_Commenced__c</fullName>
        <label>33b13 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b14_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b14 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b15_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Group Counselling - Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b15 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b16_Date_Commenced__c</fullName>
        <label>33b16 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b17_Date_Commenced__c</fullName>
        <description>Family Therapy -  Date commenced</description>
        <inlineHelpText>Family Therapy -  Date commenced</inlineHelpText>
        <label>33b17 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b18_Date_Commenced__c</fullName>
        <label>33b18 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b19_Date_Commenced__c</fullName>
        <label>33b19 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b1_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b1 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b20_Date_Commenced__c</fullName>
        <description>Aftercare - Date Commenced</description>
        <inlineHelpText>Aftercare - Date Commenced</inlineHelpText>
        <label>33b20 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b21_Date_Commenced__c</fullName>
        <description>Complimentary  Therapy - Date Commenced</description>
        <inlineHelpText>Complimentary  Therapy - Date Commenced</inlineHelpText>
        <label>33b21 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b23_Date_Commenced__c</fullName>
        <description>Family Therapy - Date Commenced</description>
        <inlineHelpText>Family Therapy - Date Commenced</inlineHelpText>
        <label>33b23 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c12_Date_Completed__c</fullName>
        <description>Medication-free therapy - Date Completed</description>
        <inlineHelpText>Medication-free therapy - Date Completed</inlineHelpText>
        <label>33c12 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c13_Date_Completed__c</fullName>
        <label>33c13 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c14_Date_Completed__c</fullName>
        <description>Individual Counselling - Date Completed</description>
        <inlineHelpText>Individual Counselling - Date Completed</inlineHelpText>
        <label>33c14 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c15_Date_Completed__c</fullName>
        <description>Group Counselling - Date Comleted</description>
        <inlineHelpText>Group Counselling - Date Comleted</inlineHelpText>
        <label>33c15 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c16_Date_Completed__c</fullName>
        <label>33c16 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c17_Date_Completed__c</fullName>
        <description>Family Therapy - Date Completed</description>
        <inlineHelpText>Family Therapy - Date Completed</inlineHelpText>
        <label>33c17 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c18_Date_Completed__c</fullName>
        <label>33c18 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c19_Date_Completed__c</fullName>
        <label>33c19 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c1_Date_Completed__c</fullName>
        <description>Brief Intervention - Date Completed</description>
        <inlineHelpText>Brief Intervention - Date Completed</inlineHelpText>
        <label>33c1 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c20_Date_Completed__c</fullName>
        <description>Aftercare - Date Completed</description>
        <inlineHelpText>Aftercare - Date Completed</inlineHelpText>
        <label>33c20 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c21_Date_Completed__c</fullName>
        <description>Complimentary Therapies - Date Completed</description>
        <inlineHelpText>Complimentary Therapies - Date Completed</inlineHelpText>
        <label>33c21 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c23_Date_Completed__c</fullName>
        <description>Family consultations - Date Completed</description>
        <inlineHelpText>Family consultations - Date Completed</inlineHelpText>
        <label>33c23 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33d12_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Medication-free therapy - Number of Sessions</description>
        <inlineHelpText>Medication-free therapy - Number of Sessions</inlineHelpText>
        <label>33d12 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d13_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>33d13 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d14_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Individual counselling - Number of Sessions</description>
        <inlineHelpText>Individual counselling - Number of Sessions</inlineHelpText>
        <label>33d14 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d15_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Group Counselling - Number of Sessions</description>
        <inlineHelpText>Group Counselling - Number of Sessions</inlineHelpText>
        <label>33d15 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d16_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Social and/or occupational reintegration - Number of Sessions</inlineHelpText>
        <label>33d16 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d17_Number_of_Sesions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Family Therapy - Number of Sessions</description>
        <inlineHelpText>Family Therapy - Number of Sessions</inlineHelpText>
        <label>33d17 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d18_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Brief intervention: individual education/awareness programme - Number of Sessions</inlineHelpText>
        <label>33d18 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d19_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Group education/awareness programme - Number of Sessions</inlineHelpText>
        <label>33d19 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d1_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Brief Intervention - Number of Sessions</description>
        <inlineHelpText>Brief Intervention - Number of Sessions</inlineHelpText>
        <label>33d1 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X34_Outcome_for_MAIN_treatment__c</fullName>
        <description>1. Treatment completed
2.  Transferred stable*(including release linking patient to other    treatment site or other prison treatment)
3.  Transferred unstable
4.  Client did not wish to attend further treatment sessions  because he/she considered him/herself to be stable 
5. Client refused to have further sessions or did not return for subsequent appointments
6. Premature exit from treatment for non-compliance.
7. Released from prison but not linked to other treatment site.
8. Died.                                9.Sentenced to prison
11. Medical transfer or medical issue.   
12. No longer lives in the area.
10.  Other______________________________

*A client is stable when he/she has engaged with the service provider, is responding to treatment, and making an effort to reduce drug/alcohol use or to remain drug/alcohol free.</description>
        <inlineHelpText>2.  *(including release linking patient to other  treatment site or other prison treatment)
4.  Client opt-out  because he/she considered him/herself to be stable 
5. Client refused  further sessions or did not return for subsequent appointments</inlineHelpText>
        <label>34 Outcome for MAIN treatment</label>
        <picklist>
            <picklistValues>
                <fullName>1. Treatment completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Transferred stable* (including release linking patient to other treatment site or other prison treatment)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Transferred unstable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Client did not wish to attend further treatment sessions because he/she considered him/herself to be stable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Client refused to have further sessions or did not return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Premature exit from treatment for non-compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Released from prison but not linked to other treatment site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Died</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Sentenced to prison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11. General medical transfer or medical issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12. No longer lives in the area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13. Mental health transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14. Prison to prison transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10. Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X36_Client_s_Condition_on_discharge__c</fullName>
        <description>36. Client’s condition at discharge or when last seen</description>
        <inlineHelpText>36. Client’s condition at discharge or when last seen</inlineHelpText>
        <label>36 Client&apos;s Condition at discharge</label>
        <picklist>
            <picklistValues>
                <fullName>1. Stable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Unstable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Died</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X37_Date_of_Final_Discharge__c</fullName>
        <description>Date of final discharge or transfer</description>
        <inlineHelpText>Date of final discharge or transfer</inlineHelpText>
        <label>37 Date of Final Discharge</label>
        <type>Date</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>Treatment-{yyyy}-{000}</displayFormat>
        <label>Treatment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestHRBFormRule.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestHRBFormRule {

    static testMethod void testTreatmentCreation1() 
    {
       Account acct1 = new Account(name='driver account');
        insert acct1;
            
        Contact driver = new Contact(AccountId=acct1.Id,lastname='Driver',firstname='apex1');
        driver.MailingStreet = '3 test screen \ntest area\ntest city';
        driver.MailingCity = 'Dublin';
        insert driver;
        Drug_HRB__c testDrug = new Drug_HRB__c (Name='testDrug');
        testDrug.DrugCode__c = '994';
        testDrug.Tableyear2012__c = true;
        insert testDrug;
        
        Treatment__c testTreatment = new Treatment__c (Contact__c=driver.id, X16_Date_of_Assessment__c=date.valueOf('2010-01-04'), X37_Date_of_Final_Discharge__c =date.valueOf('2011-07-03'));
 		testTreatment.X21a_Date_This_treatment_started__c = date.valueOf('2011-01-01');
        testTreatment.X34_outcome_for_main_treatment__c = '1. Treatment completed';
        testTreatment.X36_Client_s_Condition_on_discharge__c = '1. stable';
        testTreatment.X33b1_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b12_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b13_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b14_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b15_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b16_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b17_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b18_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b19_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b20_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b21_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33b23_Date_Commenced__c = date.valueOf('2011-01-01');
        testTreatment.X33c1_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c12_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c13_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c14_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c15_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c16_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c17_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c18_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c19_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c20_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c21_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33c23_Date_Completed__c = date.valueOf('2011-01-02');
        testTreatment.X33d1_Number_of_Sessions__c = 1;
        testTreatment.X33d12_Number_of_Sessions__c = 1;
        testTreatment.X33d13_Number_of_Sessions__c = 1;
        testTreatment.X33d14_Number_of_Sessions__c = 1;
        testTreatment.X33d15_Number_of_Sessions__c = 1;
        testTreatment.X33d16_Number_of_Sessions__c = 1;
        testTreatment.X33d17_Number_of_Sesions__c = 1;
        testTreatment.X33d18_Number_of_Sessions__c = 1;
        testTreatment.X33d19_Number_of_Sessions__c = 1;
        testTreatment.X33d20_Number_of_Sessions__c = 1;
        testTreatment.X33d21_Number_of_Sessions__c = 1;
        testTreatment.X33d23_Number_of_Sessions__c = 1;
        testTreatment.X33a_Main_Intervention__c = '1. Brief intervention';
        testTreatment.X29a_Injected_in_past_month__c = '1. Yes';
        testTreatment.X29b_Ever_injected__c = '1. Yes';
        testTreatment.X29c_Age_first_injected__c = 10;
        testTreatment.X30_Ever_shared_any_injecting_equipment__c = '1. Yes';
        testTreatment.X13_Date_of_Referral__c = date.valueOf('2010-01-03');
        testTreatment.X17a_Assessment_outcome__c = '1. something';
        testTreatment.X17b_Assessment_criterion_fulfilled__c = '1. yes';
        testTreatment.X18a_Clients_treatment_status__c = '1. something';
        testTreatment.X15_Source_of_referral__c = '4. something';
        testTreatment.X15b_If_client_referred__c = '8. something';
        testTreatment.X15b8_Other_specify__c = 'test';
        try
        {
        	insert testTreatment;
        	system.assert (false);
        }
        catch (Exception e)
        {
        	
        }
     }
}