src/objects/Treatment__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of HRB Form</description>
    <fields>
        <fullName>X21a_Date_This_treatment_started__c</fullName>
        <label>21a Date This treatment started</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b12_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b12 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b1_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b1 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c12_Date_Completed__c</fullName>
        <description>Medication-free therapy - Date Completed</description>
        <inlineHelpText>Medication-free therapy - Date Completed</inlineHelpText>
        <label>33c12 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c1_Date_Completed__c</fullName>
        <description>Brief Intervention - Date Completed</description>
        <inlineHelpText>Brief Intervention - Date Completed</inlineHelpText>
        <label>33c1 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33d12_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Medication-free therapy - Number of Sessions</description>
        <inlineHelpText>Medication-free therapy - Number of Sessions</inlineHelpText>
        <label>33d12 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d1_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Brief Intervention - Number of Sessions</description>
        <inlineHelpText>Brief Intervention - Number of Sessions</inlineHelpText>
        <label>33d1 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X37_Date_of_Final_Discharge__c</fullName>
        <description>Date of final discharge or transfer</description>
        <inlineHelpText>Date of final discharge or transfer</inlineHelpText>
        <label>37 Date of Final Discharge</label>
        <type>Date</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>Treatment-{yyyy}-{000}</displayFormat>
        <label>Treatment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestHRBFormRules3.cls
@isTest
private class TestHRBFormRules3 {

    static testMethod void TestEnsure_That_Q33c_and_Q33d_Are_Blank ()
    {
     	Treatment__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	Treatment__c checkTreatment = [select X33c1_Date_Completed__c, X33d1_Number_of_Sessions__c from Treatment__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d1_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c1_Date_Completed__c);
     	system.assertEquals (0, checkTreatment.X33d12_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c12_Date_Completed__c);
    }
}